# Continuous Integration & Deployment Workflow
name: Deploy phoTextAI to Production

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Also trigger on pull requests to main for checks

jobs:
  deploy-to-vercel:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Install Vercel CLI
        run: npm install --global vercel@latest

      - name: 3. Pull Vercel Project Environment Information
        # This command links the local directory to the Vercel project and pulls down environment variables.
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: 4. Build Project Artifacts
        # This command runs the `next build` command, creating a production-ready build.
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: 5. Deploy Project Artifacts to Vercel
        # This command uploads the built artifacts and deploys them to production.
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
